spring:
  application:
    name: mq-probe-api
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  datadog:
    metrics:
      export:
        enabled: false
        api-key: ${DATADOG_API_KEY:disabled}
        uri: https://api.datadoghq.com
  tracing:
    sampling:
      probability: 1.0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    root: INFO

mqprobe:
  idempotency:
    table-name: mq-probe-idempotency
    region: us-east-1
    record-ttl: PT24H
